ALTER TABLE leads ADD COLUMN phone TEXT NOT NULL DEFAULT '';
ALTER TABLE leads ADD COLUMN email TEXT NOT NULL DEFAULT '';
ALTER TABLE leads ADD COLUMN kind TEXT NOT NULL DEFAULT 'owner_operator';
ALTER TABLE leads ADD COLUMN agent_id TEXT NOT NULL DEFAULT '';
ALTER TABLE leads ADD COLUMN timezone TEXT NOT NULL DEFAULT 'UTC';
ALTER TABLE leads ADD COLUMN consent_sms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE leads ADD COLUMN consent_voice INTEGER NOT NULL DEFAULT 0;
ALTER TABLE leads ADD COLUMN consent_note TEXT NOT NULL DEFAULT '';
ALTER TABLE leads ADD COLUMN created_at TEXT NOT NULL DEFAULT '';
CREATE UNIQUE INDEX lead_phone ON leads(tenant_id,phone) WHERE phone != '';
CREATE TABLE sequences(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,name TEXT NOT NULL,steps TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE enrollments(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,lead_id TEXT NOT NULL,sequence_id TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE UNIQUE INDEX active_enrollment ON enrollments(tenant_id,lead_id) WHERE status IN ('active','paused');
CREATE TABLE jobs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,lead_id TEXT NOT NULL,enrollment_id TEXT,channel TEXT NOT NULL,message TEXT NOT NULL,due_at TEXT NOT NULL,status TEXT NOT NULL,provider_id TEXT,attempts INTEGER NOT NULL DEFAULT 0,error TEXT,lease_until TEXT,created_at TEXT NOT NULL);
CREATE INDEX jobs_due ON jobs(tenant_id,status,due_at);
CREATE TABLE activities(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,lead_id TEXT NOT NULL,job_id TEXT,channel TEXT NOT NULL,direction TEXT NOT NULL,text TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE pilot_settings(tenant_id TEXT PRIMARY KEY,automation_enabled INTEGER NOT NULL DEFAULT 0,daily_sms_limit INTEGER NOT NULL DEFAULT 25,daily_call_limit INTEGER NOT NULL DEFAULT 5,contact_start_hour INTEGER NOT NULL DEFAULT 8,contact_end_hour INTEGER NOT NULL DEFAULT 20);
CREATE TABLE usage_counters(tenant_id TEXT NOT NULL,day TEXT NOT NULL,channel TEXT NOT NULL,count INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(tenant_id,day,channel));
CREATE TABLE rate_limits(tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,minute TEXT NOT NULL,count INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(tenant_id,user_id,minute));
CREATE TABLE provider_events(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,event_type TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE voice_outcomes(job_id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,outcome TEXT NOT NULL,summary TEXT NOT NULL,created_at TEXT NOT NULL);
