ALTER TABLE leads ADD COLUMN company TEXT NOT NULL DEFAULT '';
ALTER TABLE leads ADD COLUMN mc_number TEXT NOT NULL DEFAULT '';
ALTER TABLE leads ADD COLUMN dot_number TEXT NOT NULL DEFAULT '';
ALTER TABLE leads ADD COLUMN fleet_size INTEGER NOT NULL DEFAULT 1;
ALTER TABLE leads ADD COLUMN niche TEXT NOT NULL DEFAULT '';
ALTER TABLE leads ADD COLUMN city TEXT NOT NULL DEFAULT '';
ALTER TABLE leads ADD COLUMN state TEXT NOT NULL DEFAULT '';
CREATE INDEX leads_company ON leads(tenant_id,company);
